// database migration for postgres (neon)
// creates every table the app needs and seeds the reference data.
// safe to run repeatedly - it is used on every deploy - because all DDL uses
// IF NOT EXISTS and all seed rows use ON CONFLICT DO NOTHING.
//
// run with: npm run migrate

const db = require('../services/db');

// note on identifiers: postgres folds unquoted names to lowercase, so
// "CREATE TABLE ChefRanks" and "FROM ChefRanks" both resolve to chefranks.
// the CA1 table named "User" had to be renamed to "Users" because USER is a
// reserved word in postgres.
const SCHEMA = `
CREATE TABLE IF NOT EXISTS ChefRanks (
  rank_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rank_name VARCHAR(255) NOT NULL,
  min_points INT NOT NULL,
  special_ability VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  points INT DEFAULT 0,
  current_rank_id INT REFERENCES ChefRanks(rank_id)
);

CREATE TABLE IF NOT EXISTS ChallengeCategory (
  category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  icon VARCHAR(20),
  description TEXT
);

CREATE TABLE IF NOT EXISTS WellnessChallenge (
  challenge_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id INT NOT NULL REFERENCES Users(user_id),
  description TEXT NOT NULL,
  points INT NOT NULL,
  category_id INT REFERENCES ChallengeCategory(category_id)
);

CREATE TABLE IF NOT EXISTS UserCompletion (
  completion_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  challenge_id INT NOT NULL REFERENCES WellnessChallenge(challenge_id),
  user_id INT NOT NULL REFERENCES Users(user_id),
  details TEXT,
  completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Badges (
  badge_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  badge_name VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS UserBadges (
  user_id INT NOT NULL REFERENCES Users(user_id),
  badge_id INT NOT NULL REFERENCES Badges(badge_id),
  earned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, badge_id)
);

CREATE TABLE IF NOT EXISTS Recipes (
  recipe_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_name VARCHAR(255) NOT NULL,
  description TEXT,
  required_points INT
);

CREATE TABLE IF NOT EXISTS UserRecipes (
  user_id INT NOT NULL REFERENCES Users(user_id),
  recipe_id INT NOT NULL REFERENCES Recipes(recipe_id),
  unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS Ingredient (
  ingredient_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  icon VARCHAR(20),
  type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS UserIngredient (
  user_id INT NOT NULL REFERENCES Users(user_id),
  ingredient_id INT NOT NULL REFERENCES Ingredient(ingredient_id),
  quantity INT DEFAULT 0,
  PRIMARY KEY (user_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS RecipeIngredient (
  recipe_id INT NOT NULL REFERENCES Recipes(recipe_id),
  ingredient_id INT NOT NULL REFERENCES Ingredient(ingredient_id),
  quantity INT DEFAULT 1,
  PRIMARY KEY (recipe_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS RecipeReview (
  review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL REFERENCES Users(user_id),
  recipe_id INT NOT NULL REFERENCES Recipes(recipe_id),
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`;

// reference data the app relies on: ranks, categories, badges, recipes and the
// sample challenges shown to visitors before they sign up.
const SEED = `
INSERT INTO ChefRanks (rank_id, rank_name, min_points, special_ability) VALUES
  (1, 'Kitchen Novice', 0, 'Basic cooking tools'),
  (2, 'Apprentice Chef', 100, 'Unlock recipe creation'),
  (3, 'Sous Chef', 300, 'Team challenge bonuses'),
  (4, 'Master Chef', 600, 'Custom challenge creation'),
  (5, 'Grand Gastromancer', 1000, 'Legendary status')
ON CONFLICT (rank_id) DO NOTHING;

INSERT INTO ChallengeCategory (category_id, name, icon, description) VALUES
  (1, 'Kitchen Prep', '📋', 'Morning routines: hydration, stretching'),
  (2, 'Market Run', '🏃', 'Physical activity: steps, exercise'),
  (3, 'Chef''s Rest', '😴', 'Sleep & mental wellness'),
  (4, 'Recipe Research', '📚', 'Learning and reading challenges'),
  (5, 'Seasonal Specials', '🎯', 'Time-limited quests')
ON CONFLICT (category_id) DO NOTHING;

INSERT INTO Badges (badge_id, badge_name, description) VALUES
  (1, 'First Challenge', 'Complete your first wellness challenge'),
  (2, 'Water Master', 'Master of hydration challenges'),
  (3, 'Fitness Star', 'Love being active')
ON CONFLICT (badge_id) DO NOTHING;

INSERT INTO Ingredient (ingredient_id, name, icon, type) VALUES
  (1, 'Fresh Berries', '🫐', 'fruit'),
  (2, 'Leafy Greens', '🥬', 'vegetable'),
  (3, 'Protein Boost', '🥩', 'protein'),
  (4, 'Whole Grains', '🌾', 'grain'),
  (5, 'Chef''s Spirit', '✨', 'special')
ON CONFLICT (ingredient_id) DO NOTHING;

INSERT INTO Recipes (recipe_id, recipe_name, description, required_points) VALUES
  (1, 'Beginner Smoothie', 'A refreshing fruit blend to start your day like a chef', 50),
  (2, 'Protein Power Bowl', 'Hearty bowl with greens and protein for sustained energy', 150),
  (3, 'Master Chef Salad', 'Elevated salad with grains and chef-style flair', 300),
  (4, 'Morning Oat Bites', 'Quick oat and honey bites for a healthy start', 25),
  (5, 'Green Detox Juice', 'Leafy greens and apple for a clean energy boost', 75),
  (6, 'Avocado Toast Deluxe', 'Creamy avocado on whole grain with a chef twist', 100),
  (7, 'Mediterranean Bowl', 'Olives, feta, and fresh veggies for a light meal', 125),
  (8, 'Stir-Fry Hero', 'Colorful veggies and protein in a savory sauce', 200),
  (9, 'Chef''s Soup of the Day', 'Hearty soup that changes with the season', 250),
  (10, 'Grain Buddha Bowl', 'Quinoa, roasted veg, and tahini for a full meal', 400),
  (11, 'Signature Pasta', 'House-made style pasta with seasonal ingredients', 500),
  (12, 'Grand Tasting Menu', 'A multi-course chef experience for top achievers', 600)
ON CONFLICT (recipe_id) DO NOTHING;

INSERT INTO Users (user_id, username, email, points, current_rank_id) VALUES
  (1, 'chef_john', 'chef_john@example.com', 0, 1),
  (2, 'baking_lover', 'baking_lover@example.com', 0, 1),
  (3, 'healthy_guy', 'healthy_guy@example.com', 0, 1)
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO WellnessChallenge (challenge_id, creator_id, description, points, category_id) VALUES
  (1, 1, 'Hydrate like a chef - Drink 8 glasses of water to stay sharp in the kitchen', 10, 1),
  (2, 1, 'Walk to the market - Take 10,000 steps to gather fresh ingredients', 15, 2),
  (3, 2, 'Rest well to cook well - Get 7+ hours of sleep for better kitchen focus', 10, 3)
ON CONFLICT (challenge_id) DO NOTHING;
`;

// the seed rows above use explicit ids, which leaves each identity sequence
// behind the highest id. bump every sequence past its table's max id so the
// next real insert does not collide with seeded data.
const RESET_SEQUENCES = `
SELECT setval(pg_get_serial_sequence('chefranks', 'rank_id'), COALESCE((SELECT MAX(rank_id) FROM ChefRanks), 1));
SELECT setval(pg_get_serial_sequence('users', 'user_id'), COALESCE((SELECT MAX(user_id) FROM Users), 1));
SELECT setval(pg_get_serial_sequence('challengecategory', 'category_id'), COALESCE((SELECT MAX(category_id) FROM ChallengeCategory), 1));
SELECT setval(pg_get_serial_sequence('wellnesschallenge', 'challenge_id'), COALESCE((SELECT MAX(challenge_id) FROM WellnessChallenge), 1));
SELECT setval(pg_get_serial_sequence('usercompletion', 'completion_id'), COALESCE((SELECT MAX(completion_id) FROM UserCompletion), 1));
SELECT setval(pg_get_serial_sequence('badges', 'badge_id'), COALESCE((SELECT MAX(badge_id) FROM Badges), 1));
SELECT setval(pg_get_serial_sequence('recipes', 'recipe_id'), COALESCE((SELECT MAX(recipe_id) FROM Recipes), 1));
SELECT setval(pg_get_serial_sequence('ingredient', 'ingredient_id'), COALESCE((SELECT MAX(ingredient_id) FROM Ingredient), 1));
SELECT setval(pg_get_serial_sequence('recipereview', 'review_id'), COALESCE((SELECT MAX(review_id) FROM RecipeReview), 1));
`;

async function migrate() {
    console.log('Running migration...');

    await db.raw(SCHEMA);
    console.log('  tables ready');

    await db.raw(SEED);
    console.log('  reference data seeded');

    await db.raw(RESET_SEQUENCES);
    console.log('  id sequences aligned');

    console.log('Migration complete.');
}

// only run automatically when executed directly (npm run migrate), so tests can
// import and call migrate() themselves
if (require.main === module) {
    migrate()
        .then(() => db.end())
        .then(() => process.exit(0))
        .catch((error) => {
            console.error('Migration failed:', error.message);
            process.exit(1);
        });
}

module.exports = { migrate };
